name: Pull request label

on:
  - pull_request
    branches:
      - master

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Label pull request according to `labeler.yml`
        uses: actions/labeler@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
